<?php

/* r25sync.module, v. RC2, bamberj, 05.12.2017 */

/**
 * @file
 * Module file for r25sync.
 */
 
/**
* Implements hook_cron().
*/
function r25sync_cron() {
	$queue = \Drupal::queue('r25sync_queue');
	
	if ($queue->numberOfItems() == 0) {
		$config = \Drupal::config('r25sync.configuration');
		$max = $config->get('end_dt');
		for($i = 0; $i < $max; $i++) {
			$queue->createItem(
				array(
					'op' => 'fetch', 
					'start_dt' => $i,
				)
			);
		}
		
		/* evaluate existing nodes */
		$nodes = \Drupal::entityTypeManager()
			->getStorage('node')
			->loadByProperties(array('type' => "r25_event"));
	
		foreach ($nodes as $node) {
			$queue->createItem(
				array(
					'op' => 'eval', 
					'nid' => $node->id(),
				)
			);
		}
	}
}